# cmd:ansible-galaxy "${ansible_type}" install -r

collections:
  - name: elreydetoda.virtualization
  # because of: https://github.com/ansible-collections/community.general/blob/main/scripts/inventory/packet_net.py
  - name: community.general
    version: 6.5.0
  - name: ansible.posix
    version: 1.5.1

roles:
  - name: elreydetoda.textbelt
  # - name: diodonfrost.vagrant
  #   version: 1.5.0
